CREATE TABLE IF NOT EXISTS call_summaries (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    processing_id VARCHAR(64) NOT NULL UNIQUE,
    input_type VARCHAR(32) NOT NULL DEFAULT 'api_request',
    audio_file_name VARCHAR(255) NOT NULL,
    audio_content_type VARCHAR(128) NULL,
    stored_audio_path VARCHAR(1024) NULL,
    caller VARCHAR(64) NULL,
    extension_number VARCHAR(64) NULL,
    callee VARCHAR(64) NULL,
    call_started_at DATETIME NULL,
    call_ended_at DATETIME NULL,
    audio_duration_seconds DECIMAL(10,3) NULL,
    detected_language VARCHAR(32) NULL,
    speech_recognition_model VARCHAR(128) NOT NULL,
    summary_generation_model VARCHAR(255) NOT NULL,
    summary_model_backend VARCHAR(64) NULL,
    full_transcript LONGTEXT NULL,
    structured_call_summary LONGTEXT NULL,
    plain_call_summary LONGTEXT NULL,
    speaker_summary_list_json LONGTEXT NULL,
    speaker_segment_list_json LONGTEXT NULL,
    processing_time_ms INT NULL,
    processing_status VARCHAR(32) NOT NULL,
    error_message VARCHAR(1000) NULL,
    result_created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_call_summaries_result_created_at (result_created_at),
    KEY idx_call_summaries_input_type (input_type),
    KEY idx_call_summaries_processing_status (processing_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS stt_training_samples (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    call_summary_id BIGINT NOT NULL,
    request_id VARCHAR(64) NOT NULL,
    filename VARCHAR(255) NOT NULL,
    audio_path VARCHAR(1024) NULL,
    segment_index INT NULL,
    speaker VARCHAR(64) NULL,
    start_seconds DECIMAL(10,3) NULL,
    end_seconds DECIMAL(10,3) NULL,
    original_text LONGTEXT NULL,
    corrected_text LONGTEXT NOT NULL,
    note VARCHAR(1000) NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'queued',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_stt_training_samples_call_summary_id (call_summary_id),
    KEY idx_stt_training_samples_segment (call_summary_id, segment_index),
    KEY idx_stt_training_samples_status (status),
    CONSTRAINT fk_stt_training_samples_call_summary_id
        FOREIGN KEY (call_summary_id) REFERENCES call_summaries(id)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
